[package]
name = "cog"
version = "0.0.1"
authors = ["Brandon Sanderson <bas.bsanders@gmail.com>"]

[dependencies]
ncurses = "*"
nom = "*"
docopt_macros = "*"
docopt = "*"
rustc-serialize = "*"
astar = "*"
